# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Code4Nation
tagline:			 'How Can We Help?'
description:         'Indonsian Geek Movement, for Better Nation'
url:                 http://code4nation.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Code4Nation
  url:               http://code4nation.org
  email:             lord@code4nation.org

# Custom vars
version:             1.0.0
